_BASE_: Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN: False
  DEVICE: cpu

CUDNN_BENCHMARK: False

OUTPUT_DIR: logs/vehicle
